### ISSUE TITLE
multiresolutioninterface.MultiResolutionImageReader() can't be imported

### ISSUE THREAD

**Issue by dddavid4real** [davidtellez/neural-image-compression#3]
This function is a .cpp file and it can't be directly used in the python implementation. Why did the author just directly use it in _vectorize_wsi.py_ ? And how to solve this problem?

**Comment by MohammedHAlali** [comment]
You need to install ASAP, https://github.com/computationalpathologygroup/ASAP

**Comment by dddavid4real** [comment]
> You need to install ASAP, https://github.com/computationalpathologygroup/ASAP

Thanks! By the way, do you mean download the ASAP released package on my linux server? Or should I download it into the python site-packages directory? I have been working on this problem for the last two days and It kinda driving me crazy. Thank you for your kind advice.

**Comment by MohammedHAlali** [comment]
check out this issue: https://github.com/computationalpathologygroup/ASAP/issues/187

or the full list of issues:
https://github.com/computationalpathologygroup/ASAP/issues?page=2&q=is%3Aissue+is%3Aclosed

**Comment by dddavid4real** [comment]
> check out this issue: [computationalpathologygroup/ASAP#187](https://github.com/computationalpathologygroup/ASAP/issues/187)
> 
> or the full list of issues: https://github.com/computationalpathologygroup/ASAP/issues?page=2&q=is%3Aissue+is%3Aclosed

Thank you so much!
